import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import HeaderNavbar from "@/components/HeaderNavbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <>
       <HeaderNavbar/>
        {children}
       </>
        </body>
    </html>
  );
}
